minVersion: 0.34.1
github:
  owner: getsentry
  repo: jsonnet-libs
changelogPolicy: auto
preReleaseCommand: bash sbin/bump-version.sh
targets:
  - name: github
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
