---
minVersion: 0.34.1
github:
  owner: getsentry
  repo: jsonnet-libs
changelogPolicy: auto
preReleaseCommand: bash sbin/bump-version-jsonnet.sh
releaseBranchPrefix: release-sentry-jsonnet
targets:
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
