#!/usr/bin/env python
import os
import sys

try:
    path, start = sys.argv[1:]
except ValueError:
    try:
        (path,) = sys.argv[1:]
    except ValueError:
        exit("Usage: relpath $PATH [$START]")
    else:
        start = os.environ["PWD"]

# we get really weird behavior with a relative 'start'
assert os.path.isabs(start), start

print(os.path.relpath(path, start))
