#!/bin/bash
set -eEuo pipefail
VIRTUAL_ENV="${1:-$VIRTUAL_ENV}"
PYTHON="${PYTHON:-python3.8}"
PYTHON="$(which $PYTHON)"

set -x
python -m venv "$VIRTUAL_ENV"
"$VIRTUAL_ENV"/bin/pip install --upgrade pip pip-tools
