#!/bin/bash
set -eEuo pipefail
VIRTUAL_ENV="${1:-$VIRTUAL_ENV}"
PYTHON="${PYTHON:-python3.8}"
PYTHON="$(which $PYTHON)"

set -x
virtualenv --prompt="$PROJECT" --python=$PYTHON "$VIRTUAL_ENV"
"$VIRTUAL_ENV"/bin/pip install --upgrade pip pip-tools
