# TODO: This one and sentry_jsonish are almost the same.
# A reusable flow would help.
name: build sentry_jsonnet

on:
  push:
    branches:
      - main
      - release-sentry-jsonnet/**

jobs:
  dist:
    name: Create wheel and source distribution for sentry-jsonnet
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Prepare artifacts"
        working-directory: ./sentry_jsonnet
        run: |
          pip install wheel
          pip install build
          python -m build --wheel
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ github.sha }}
          path: sentry_jsonnet/dist/*
